### ISSUE TITLE
slow frameworks/base and missing things in system/security/keymaster 

### ISSUE THREAD

**Issue by adeii** [GlazeOS/manifest#2]
With brunch <device>, building with Jack, freezes at .../framework_intermediates/with-local/classes.jack.
with make frameworks, it builds normaly, pritty fast, but it deletes framework.* for brunch <device>

 system/security/keymaster project need to be updated: missing ignored *_SOTER_* tags for switch
(Solved with: https://github.com/AOSP-RRO/platform_system_keymaster/blob/0e96ab564a2e14d8d281ac777705d1c638bd543e/keymaster_enforcement.cpp#L338 )
 and also missing AuthorizationSet.Union and .Difference methods.
Solved with: https://android.googlesource.com/platform/system/keymaster/+/391a367df2352bed7e70885493421892a1cdaffc%5E!/

**Comment by NoelMacwan** [comment]
@adeii Thanks for pointing out.

Changes has been merged :+1:
